/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.edustream;

/**
 *
 * @author Usuario
 */

//Todas las librerias necesarias
import java.util.Scanner;
import java.sql.*;
import javax.swing.JOptionPane;

public class formLogin extends javax.swing.JFrame {

    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edustreamLabel = new javax.swing.JLabel();
        inicioSesionLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        iniciarSesionButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edustreamLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        edustreamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edustreamLabel.setText("EDUSTREAM");

        inicioSesionLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        inicioSesionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioSesionLabel.setText("--------INICIO DE SESION--------");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Email");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        passwordLabel.setText("Password");

        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        passwordTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        iniciarSesionButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        iniciarSesionButton.setText("Iniciar Sesion");
        iniciarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionButtonActionPerformed(evt);
            }
        });

        salirButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salirButton.setText("Salir"); // NOI18N
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(edustreamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inicioSesionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iniciarSesionButton)
                                .addGap(103, 103, 103)
                                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(edustreamLabel)
                .addGap(18, 18, 18)
                .addComponent(inicioSesionLabel)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordTextField))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarSesionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        
        //Asegurandonos que el usuario efectivamente desea salir del programa
        int opcion = JOptionPane.showConfirmDialog(this, "¿Deseas salir del programa?", "", JOptionPane.YES_NO_OPTION);
        
        if(opcion == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_salirButtonActionPerformed

    private void iniciarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionButtonActionPerformed
        // TODO add your handling code here:
        
        //Primera parte, donde hacemos revision de que el usuario haya ingresado texto en ambos campos
        //para el ingreso a la pagina principal.
        String emailTexto = emailTextField.getText().trim();
        String salirTexto = new String(passwordTextField.getPassword()).trim();
        
        if(emailTexto.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste texto en el campo de usuario");
        }else if(salirTexto.isEmpty()){
            JOptionPane.showMessageDialog(this,"No ingresaste texto en el campo de la contracena");
        }
        
        /* Primero se hará la consulta a la base de datos de la existencia del usuario
           y luego se cerrarán las conexiones con el metodo try-with-resources.  
        */
        String sql = "SELECT * FROM usuarios WHERE email = ? AND password = ?";
            try(Connection con = Conexion.getConexion(); PreparedStatement ps = con.prepareStatement(sql)){
            
                ps.setString(1, emailTexto);
                ps.setString(2, salirTexto);
                ResultSet rs = ps.executeQuery();
    
                if (rs.next()){
                    Usuario user = new Usuario();
                    user.setId(rs.getInt("id_usuario"));
                    user.setNombre(rs.getString("nombre"));
                    user.setRol(rs.getString("rol"));
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
    }
        
    }//GEN-LAST:event_iniciarSesionButtonActionPerformed
        
    public class Usuario{
        private int id; 
        private String nombre; 
        private String email; 
        private String rol; 
        
        public Usuario(){
            
        }
        
        //Contructores, getters y setters
        public Usuario(int id, String nombre, String email, String rol) {
            this.id = id;
            this.nombre = nombre;
            this.email = email;
            this.rol = rol;
        }

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

        public String getNombre() {
            return nombre;
        }

        public void setNombre(String nombre) {
            this.nombre = nombre;
        }

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }

        public String getRol() {
            return rol;
        }

        public void setRol(String rol) {
            this.rol = rol;
        }
        
        
    }
    
    //Conexion entre Java y MySQL
    public class Conexion{
        private static final String URL = "jdbc:mysql://localhost:3306/edustream_db";
        private static final String USER = "root";
        private static final String PASS = "tu_password";
        
        public static Connection getConexion() throws SQLException{
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                return DriverManager.getConnection(URL, USER, PASS);
            }catch(ClassNotFoundException e){
                throw new SQLException(e);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel edustreamLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton iniciarSesionButton;
    private javax.swing.JLabel inicioSesionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
