/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.edustream;

/**
 *
 * @author Usuario
 */

import javax.swing.JOptionPane;

public class formEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form formEstudiante
     */
    public formEstudiante() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelnfo = new javax.swing.JPanel();
        labelEsdustream = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        botonNotas = new javax.swing.JButton();
        botonCambiarContrasena = new javax.swing.JButton();
        botonFinalSesion = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        panelNotas = new javax.swing.JPanel();
        tablaInfoMateria = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelContrasena = new javax.swing.JPanel();
        labelPrimeraContrasena = new javax.swing.JLabel();
        labelNuevaContrasena = new javax.swing.JLabel();
        textFieldContrasenaActual = new javax.swing.JPasswordField();
        textFieldContrasenaNueva = new javax.swing.JPasswordField();
        botonConfirmarContrasena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelnfo.setBackground(new java.awt.Color(153, 153, 153));

        labelEsdustream.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelEsdustream.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEsdustream.setText("EduStream");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("ZXCVBNMAS ZXCVBNMASDFGHJK");

        labelRol.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        labelRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRol.setText("ESTUDIANTE");

        javax.swing.GroupLayout panelnfoLayout = new javax.swing.GroupLayout(panelnfo);
        panelnfo.setLayout(panelnfoLayout);
        panelnfoLayout.setHorizontalGroup(
            panelnfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEsdustream)
                .addGroup(panelnfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelnfoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelnfoLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(labelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelnfoLayout.setVerticalGroup(
            panelnfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnfoLayout.createSequentialGroup()
                .addGroup(panelnfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelnfoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelEsdustream))
                    .addGroup(panelnfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRol)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        botonNotas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonNotas.setText("Mis Notas");
        botonNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNotasActionPerformed(evt);
            }
        });

        botonCambiarContrasena.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonCambiarContrasena.setText("Cambiar Contraseña");
        botonCambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarContrasenaActionPerformed(evt);
            }
        });

        botonFinalSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonFinalSesion.setText("Finalizar Sesion");
        botonFinalSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalSesionActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "CURSO", "NOTA", "ESTADO", "PROFESOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInfoMateria.setViewportView(jTable1);

        javax.swing.GroupLayout panelNotasLayout = new javax.swing.GroupLayout(panelNotas);
        panelNotas.setLayout(panelNotasLayout);
        panelNotasLayout.setHorizontalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
            .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotasLayout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(tablaInfoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        panelNotasLayout.setVerticalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
            .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotasLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablaInfoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        labelPrimeraContrasena.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelPrimeraContrasena.setText("Contraseña Actual");

        labelNuevaContrasena.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelNuevaContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNuevaContrasena.setText("Nueva Contraseña");

        textFieldContrasenaActual.setText("jPasswordField1");
        textFieldContrasenaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContrasenaActualActionPerformed(evt);
            }
        });

        textFieldContrasenaNueva.setText("jPasswordField1");

        botonConfirmarContrasena.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        botonConfirmarContrasena.setText("Confirmar Cambios");
        botonConfirmarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContrasenaLayout = new javax.swing.GroupLayout(panelContrasena);
        panelContrasena.setLayout(panelContrasenaLayout);
        panelContrasenaLayout.setHorizontalGroup(
            panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContrasenaLayout.createSequentialGroup()
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonConfirmarContrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelContrasenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNuevaContrasena)
                            .addComponent(labelPrimeraContrasena, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldContrasenaActual)
                    .addComponent(textFieldContrasenaNueva, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelContrasenaLayout.setVerticalGroup(
            panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContrasenaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrimeraContrasena)
                    .addComponent(textFieldContrasenaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(panelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevaContrasena)
                    .addComponent(textFieldContrasenaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(botonConfirmarContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(panelContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addComponent(panelNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelnfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFinalSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelnfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botonCambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botonFinalSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFinalSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalSesionActionPerformed
        // TODO add your handling code here:
        //Codigo basico para cerrar sesion y regresar al login
        int opcion = JOptionPane.showConfirmDialog(this, "¿Deseas salir del programa?", "", JOptionPane.YES_NO_OPTION);
        
        if(opcion == JOptionPane.YES_OPTION){
            formLogin login = new formLogin();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_botonFinalSesionActionPerformed

    private void botonNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNotasActionPerformed
        // TODO add your handling code here:
        panelNotas.setVisible(true);
        panelContrasena.setVisible(false);
    }//GEN-LAST:event_botonNotasActionPerformed

    private void botonMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMatricularActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonMatricularActionPerformed

    private void botonCambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarContrasenaActionPerformed
        // TODO add your handling code here:
        panelNotas.setVisible(false);
        panelContrasena.setVisible(true);
    }//GEN-LAST:event_botonCambiarContrasenaActionPerformed

    private void botonConfirmarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarContrasenaActionPerformed
        // TODO add your handling code here:
        //Codigo para verificar que el usuario no haya dejado espacios en blanco 
        String contrasenaActual = new String(textFieldContrasenaNueva.getPassword()).trim();
        String contrasenaVieja = new String(textFieldContrasenaActual.getPassword()).trim();
        
        if(contrasenaVieja.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste tu contrasena actual");
        }else if(contrasenaVieja.isEmpty() || contrasenaActual.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste tu contrasena actual y tampoco en el nuevo");
        }else if(contrasenaActual.isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste texto para tu nueva contrasena");
        }
        
        
        
    }//GEN-LAST:event_botonConfirmarContrasenaActionPerformed

    private void textFieldContrasenaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContrasenaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldContrasenaActualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCambiarContrasena;
    private javax.swing.JButton botonConfirmarContrasena;
    private javax.swing.JButton botonFinalSesion;
    private javax.swing.JButton botonNotas;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelEsdustream;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNuevaContrasena;
    private javax.swing.JLabel labelPrimeraContrasena;
    private javax.swing.JLabel labelRol;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelContrasena;
    private javax.swing.JPanel panelNotas;
    private javax.swing.JPanel panelnfo;
    private javax.swing.JScrollPane tablaInfoMateria;
    private javax.swing.JPasswordField textFieldContrasenaActual;
    private javax.swing.JPasswordField textFieldContrasenaNueva;
    // End of variables declaration//GEN-END:variables
}
